#!/command/with-contenv bash
echo "Syncing SQLite WAL"

if [[ $BUCKET_LOCATION ]]; then
  /opt/bin/litestream replicate /tmp/.ht.sqlite $BUCKET_LOCATION
else
  echo "BUCKET_LOCATION env var not set, skipping litestream sync"
  /usr/bin/sleep 99d
fi

