name: Trigger auto deployment for arontsang-wordpress

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/arontsang-wordpress-AutoDeployTrigger-d155fb41-ac9a-4dea-aa32-e2591d0a017a.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: tsangwordpress.azurecr.io
          username: ${{ secrets.ARONTSANGWORDPRESS_REGISTRY_USERNAME }}
          password: ${{ secrets.ARONTSANGWORDPRESS_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tsangwordpress.azurecr.io/peachpie-wordpress:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ARONTSANGWORDPRESS_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n arontsang-wordpress -g wordpress --server tsangwordpress.azurecr.io --username  ${{ secrets.ARONTSANGWORDPRESS_REGISTRY_USERNAME }} --password ${{ secrets.ARONTSANGWORDPRESS_REGISTRY_PASSWORD }}
            az containerapp update -n arontsang-wordpress -g wordpress --image tsangwordpress.azurecr.io/peachpie-wordpress:${{ github.sha }}
